cloudProvider:
  storageClass: default-rwo

clusterName: px-cluster              # This is the default. please change it to your cluster name.
namespace: portworx              # This is the default. Change this if you don't plan to install in kube-system

storage:
  usefileSystemDrive: false         # true/false Instructs PX to use an unmounted Drive even if it has a filesystem.
  usedrivesAndPartitions: false     # Defaults to false. Change to true and PX will use unmounted drives and partitions.
  drives: "type=gp2,size=20"        # NOTE: This is a ";" seperated list of drives. For eg: "/dev/sda;/dev/sdb;/dev/sdc" Defaults to use -A switch.
                                    # To have drives automatically created specify the drive spec. For Eg: "type=gp2,size=150" or "type=io1,size=100,iops=2000"
  journalDevice:
  maxStorageNodesPerZone:

network:
  dataInterface: none               # Name of the interface <ethX>
  managementInterface: none         # Name of the interface <ethX>

secretType: k8s                     # Defaults to k8s, but can be aws-kms/k8s/none
envVars: none                       # NOTE: This is a ";" seperated list of environment variables. For eg: MYENV1=myvalue1;MYENV2=myvalue2

csi: true                          # Enable CSI

internalKVDB: true                  # internal KVDB

customRegistryURL: 
registrySecret:

serviceAccount:

repo:
  enterprise: docker.io/portworx
  dr: docker.io/portworx


versions:
  operator: "1.10.4"
  enterprise: "2.13.0"
  ociMon: "2.13.0"
  autoPilot: "1.3.7"
  stork: "2.12.4"